name = "video"
compatibility_date = "2026-08-21"
workers_dev = false
preview_urls = true
routes = [
  { pattern = "video.trombett.org", custom_domain = true }
]

[observability]
enabled = true

[assets]
directory = "./public"
